Repository road-maker/road-maker-react-typescript, pull requests merged in 2023-07, with the labels that each got.

#8 #2 Design: 회원가입 페이지
  src/App.test.tsx
  src/App.tsx
  src/components/LoginForm.tsx
  src/components/ResetInfoForm.tsx
  src/components/SignupForm.tsx
  src/pages/main/index.tsx
  yarn.lock
Labels: 🎨Design, 🙆‍♀️Merge Needed

#9 [#3] [#4] Style : 로그인, 회원가입 페이지
  .eslintrc.json
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/hotfix.md
  .gitignore
  package.json
  public/index.html
  src/App.test.tsx
  src/App.tsx
  src/components/LoginForm.tsx
  src/components/ResetInfoForm.tsx
  src/components/SignupForm.tsx
  src/index.tsx
  src/pages/main/index.tsx
  src/types/types.ts
  yarn.lock
Labels: 💅Style, ⚡Simple

#12 [#11] merge 반영
  .env
  .eslintrc.json
  .github/workflows/s3Build.yml
  .gitignore
  package.json
  src/App.tsx
  src/auth/useAuth.tsx
  src/axiosInstance/constants.js
  src/components/LoginForm.tsx
  src/components/editor/Editor.tsx
  src/components/user/hooks/useUser.tsx
  src/pages/editor/index.tsx
  src/theme/GlobalStyle.js
  src/theme/theme.js
  src/user-storage/index.ts
  yarn.lock
Labels: 🛠️Fix

#15 [#14] Feat: React Flow 라이브러리 적용 테스트, autoformating 적용
  package.json
  src/components/editor/Editor.tsx
  src/components/editor/Minimap.tsx
  src/components/textEditor/index.tsx
  src/pages/editor/index.tsx
  tsconfig.json
Labels: ❇️Feat

#20 [#19] Feat : 회원가입기능 완료, BE랑 연동 성공, 타입 에러 해결
  .env
  src/App.tsx
  src/auth/useAuth.tsx
  src/components/LoginForm.tsx
  src/components/SignupForm.tsx
  src/components/common/hooks/useInput.tsx
  src/components/editor/Editor.tsx
  src/components/modals/Sucess.tsx
  src/components/user/hooks/useUser.tsx
  src/pages/signup/index.tsx
  src/react-query/constants.js
  src/types/types.ts
Labels: ❇️Feat, 🙆‍♀️Merge Needed

#22 Ts error pyotato
  src/auth/useAuth.tsx
  src/components/LoginForm.tsx
Labels: ❇️Feat, 🙆‍♀️Merge Needed

#26 [#10] Design: 전체적인 디자인 완료
  package.json
  public/img/logo.png
  src/App.tsx
  src/components/LoginForm.tsx
  src/components/SignupForm.tsx
  src/components/editor/Editor.tsx
  src/components/modals/Sucess.tsx
  src/components/user/hooks/useUser.tsx
  src/pages/login/index.tsx
  src/pages/main/header.tsx
  src/pages/main/index.tsx
  src/pages/main/roadmapRecommendation.tsx
Labels: 💅Style, 🙆‍♀️Merge Needed

#33 [#25] 로그인/회원가입 기능 연동
  package.json
  src/App.tsx
  src/auth/useAuth.tsx
  src/axiosInstance/index.ts
  src/components/LoginForm.tsx
  src/components/editor/CustonNode.jsx
  src/components/editor/ResizableNodeSelected.tsx
  src/components/editor/RoadMapEditor.tsx
  src/components/pretest/monaco/Editor.tsx
  src/components/textEditor/Tiptap.tsx
  src/components/textEditor/index.tsx
  src/components/user/hooks/useUser.tsx
  src/pages/editor/index.tsx
  src/store.ts
  src/types/types.ts
  src/user-storage/index.ts
Labels: ❇️Feat

#35 [#27] Fix : build issues due to eslint
  src/components/editor/RoadMapEditor.tsx
  src/components/pretest/codeBox/index.tsx
Labels: 🛠️Fix, 🎇Build

#38 [#12] Feat: jwt 토큰 연결 완료
  src/App.tsx
  src/auth/useAuth.tsx
  src/components/LoginForm.tsx
  src/components/SignupForm.tsx
  src/components/editor/RoadMapEditor.tsx
  src/components/pretest/codeBox/index.tsx
  src/pages/login/index.tsx
  src/pages/main/header.tsx
Labels: ❇️Feat

#39 [#12] Build : eslint 경고 코드 주석
  src/components/LoginForm.tsx
  src/components/SignupForm.tsx
Labels: 🎇Build

#41 Global editor style pyotato
  src/components/SignupForm.tsx
  src/components/pretest/codeBox/index.tsx
  src/pages/roadmap/index.tsx
Labels: 🙆‍♀️Merge Needed

#53 [#52] Chore : 안쓰는 모듈 지우기
  src/App.tsx
  src/components/pretest/array copy/index copy.tsx
  src/pages/roadmap/index.tsx
Labels: bug, 🧹Chore

#54 [#52] Remove : 안쓰는 모듈 지우기
  src/components/modals/Sucess.tsx
  src/components/pretest/array/index copy.tsx
  src/components/pretest/codeBox/store.ts
  src/components/pretest/codeBox_/TextEditor.tsx
  src/components/pretest/codeBox_/index copy.tsx
  src/components/pretest/codeBox_/index.tsx
  src/components/textEditor/Tiptap.tsx
Labels: 👻Remove

#55 [#27] Design : ui 개선, [#51] Feat : chatgpt api 연동 준비
  .env
  package.json
  src/App.tsx
  src/assets/Rejection.svg
  src/components/editor/ColorSelectorNode.jsx
  src/components/editor/CustomNode.tsx
  src/components/editor/Minimap.tsx
  src/components/editor/ResizableNodeSelected.tsx
  src/components/editor/RoadMapEditor copy.tsx
  src/components/editor/RoadMapEditor.tsx
  src/components/editor/types.ts
  src/components/pretest/array copy/index.tsx
  src/components/pretest/codeBox/CodeBox.tsx
  src/components/pretest/codeBox/Wrapper.tsx
  src/components/pretest/codeBox/index.tsx
  src/components/pretest/codeBox/store.ts
  src/components/pretest/monaco/Editor.tsx
  src/components/pretest/tiptap copy/Editor.tsx
  src/components/pretest/tiptap copy/Editor_new.tsx
  src/components/pretest/tiptap copy/extensions/AnnotationItem.ts
  src/components/pretest/tiptap copy/extensions/AnnotationPlugin.ts
  src/components/pretest/tiptap copy/extensions/AnnotationState.ts
  src/components/pretest/tiptap copy/extensions/collaboration-annotation.ts
  src/components/pretest/tiptap/Editor.tsx
  src/components/pretest/tiptap/Editor_new.tsx
  src/components/pretest/tiptap/extensions/AnnotationItem.ts
  src/components/pretest/tiptap/extensions/AnnotationPlugin.ts
  src/components/pretest/tiptap/extensions/AnnotationState.ts
  src/components/pretest/tiptap/extensions/collaboration-annotation.ts
  src/components/prompts/hooks/usePrompt.ts
  src/components/prompts/hooks/usePromptResponse.ts
  src/components/textEditor copy/Tiptap.tsx
  src/components/textEditor copy/index.tsx
  src/components/textEditor/MenuBar.tsx
  src/components/textEditor/index.tsx
  src/components/user/hooks/useUser.ts
  src/index.css
  src/index.tsx
  src/pages/editor/index.tsx
  src/pages/error/index.tsx
  src/pages/login/index.tsx
  src/pages/main/header.tsx
  src/pages/roadmap/details/index.tsx
  src/pages/roadmap/editor/index.tsx
  src/pages/roadmap/index.tsx
  src/setProxy.js
  src/storage/gpt-storage/index.ts
  src/storage/user-storage/index.ts
  src/types/types.ts
Labels: ❇️Feat

#56 [#51] Remove : 파일 제거
  src/pages/main/roadmapProcess.tsx
Labels: 👻Remove

#57 [#51] Remove : 파일 제거
  src/pages/roadmap/details/index.tsx
Labels: 👻Remove

#64 [#63] post 기능 연동
  package.json
  src/App.tsx
  src/auth/useAuth.ts
  src/axiosInstance/index.ts
  src/components/common/hooks/usePatchUser.ts
  src/components/common/hooks/useRoadmapEditor.tsx
  src/components/editor/RoadMapEditor.tsx
  src/components/editor/editorhyemin.tsx
  src/components/editor/editorseoin.tsx
  src/components/editor/types.ts
  src/components/prompts/hooks/usePrompt.ts
  src/components/roadmaps/hooks/useRoadmap.ts
  src/components/user/editUserProfile.tsx
  src/components/user/forms/LoginForm.tsx
  src/components/user/hooks/useUser.ts
  src/components/user/userProfile.tsx
  src/layout/mainLayout/header/header.tsx
  src/layout/mainLayout/index.tsx
  src/pages/main/commentPage.tsx
  src/pages/main/header.tsx
  src/pages/roadmap/editor/index.tsx
  src/pages/roadmap/view/postedRoadmap.tsx
  src/react-query/constants.js
  src/types/types.ts
Labels: ❇️Feat

#65 Initialmerge
  package-lock.json
  package.json
  src/App.tsx
  src/auth/useAuth.ts
  src/axiosInstance/constants.js
  src/axiosInstance/index.ts
  src/components/common/Loading.tsx
  src/components/common/hooks/usePatchUser.ts
  src/components/common/hooks/useRoadmapEditor.tsx
  src/components/editor/CustomNode.tsx
  src/components/editor/Minimap.tsx
  src/components/editor/ResizableNodeSelected.tsx
  src/components/editor/RoadMapEditor copy.tsx
  src/components/editor/RoadMapEditor.tsx
  src/components/editor/editorhyemin.tsx
  src/components/editor/editorseoin.tsx
  src/components/editor/previous.tsx
  src/components/editor/types.ts
  src/components/modals/Sucess.tsx
  src/components/prompts/hooks/usePrompt.ts
  src/components/roadmaps/hooks/useRoadMapResponse.ts
  src/components/roadmaps/hooks/useRoadmap.ts
  src/components/user/editUserProfile.tsx
  src/components/user/forms/LoginForm.tsx
  src/components/user/forms/ResetInfoForm.tsx
  src/components/user/forms/SignupForm.tsx
  src/components/user/hooks/useUser.ts
  src/components/user/userProfile.tsx
  src/components/user/userRoadmap.tsx
  src/components/user/userinfo.tsx
  src/layout/index.js
  src/layout/mainLayout/header/header.tsx
  src/layout/mainLayout/index.tsx
  src/pages/error/index.tsx
  src/pages/login/index.tsx
  src/pages/main/commentPage.tsx
  src/pages/main/header.tsx
  src/pages/main/index.tsx
  src/pages/main/roadmapRecommendation.tsx
  src/pages/resetInfo/index.tsx
  src/pages/roadmap/editor/index.tsx
  src/pages/roadmap/view/completeRoadmap.tsx
  src/pages/roadmap/view/customNode.tsx
  src/pages/roadmap/view/multiSelectionToolbar.tsx
  src/pages/roadmap/view/postedRoadmap.tsx
  src/pages/roadmap/view/userRoadmap.tsx
  src/pages/signup/index.tsx
  src/react-query/constants.js
  src/storage/roadmap-storage/index.ts
  src/types/types.ts
  store.ts
Labels: 🙆‍♀️Merge Needed

#74 [#72] Remove : remove unused files
  public/index.html
  src/components/pretest/array/index.tsx
Labels: 👻Remove

#75 [#63] Feat : get 완성된 로드맵 상세보기 정보 가져오기
  src/App.tsx
  src/auth/useAuth.ts
  src/components/common/hooks/useRoadmapEditor.tsx
  src/components/editor/RoadMapEditor.tsx
  src/components/editor/editorseoin.tsx
  src/components/editor/types.ts
  src/components/prompts/hooks/usePrompt.ts
  src/components/prompts/hooks/usePromptResponse.ts
  src/components/roadmaps/hooks/useRoadmap.ts
  src/components/user/hooks/usePatchUser.ts
  src/components/user/hooks/useUser.ts
  src/layout/mainLayout/header/header.tsx
  src/pages/main/roadmapRecommendation.jsx
  src/react-query/queryClient.ts
  src/storage/gpt-storage/index.ts
  src/types/types.ts
Labels: ❇️Feat

#77 [#76] Fix : 메인페이지 데이터 가져올때 빈 map 돌릴려는 버그 fix
  package-lock.json
  public/index.html
  src/App.tsx
  src/auth/useAuth.ts
  src/components/common/hooks/usePatchUser.ts
  src/components/common/hooks/useRoadmapEditor.tsx
  src/components/editor/RoadMapEditor.tsx
  src/components/editor/editorseoin.tsx
  src/components/editor/types.ts
  src/components/pretest/array/index.tsx
  src/components/prompts/hooks/usePrompt.ts
  src/components/prompts/hooks/usePromptResponse.ts
  src/components/roadmaps/hooks/useRoadmap.ts
  src/components/user/editUserProfile.tsx
  src/components/user/forms/LoginForm.tsx
  src/components/user/hooks/usePatchUser.ts
  src/components/user/hooks/useUser.ts
  src/components/user/userRoadmap.tsx
  src/layout/mainLayout/header/header.tsx
  src/pages/main/RoadMapPosts/InfiniteRoadmaps.jsx
  src/pages/main/RoadMapPosts/Roadmaps.jsx
  src/pages/main/header.tsx
  src/pages/main/roadmapRecommendation.jsx
  src/pages/roadmap/editor/index.tsx
  src/pages/roadmap/view/postedRoadmap.tsx
  src/pages/roadmap/view/userRoadmap.tsx
  src/react-query/queryClient.ts
  src/storage/gpt-storage/index.ts
  src/types/types.ts
Labels: 🛠️Fix
